### ISSUE TITLE
Video time links aren't working

### ISSUE THREAD

**Issue by nedtwigg** [mytakedotorg/mytakedotorg#205] opened 2018-07-21 00:32 UTC
Ruh-roh.  I wonder if YouTube's API changed?

Video links aren't playing in the right place for me.  Scrubbing is also not working.  This is true:

- in prod: https://mytake.org/foundation-v1/presidential-debate-kennedy-nixon-1-of-4/2888.000-2910.500
- in staging: https://mytake-staging.herokuapp.com/foundation-v1/presidential-debate-kennedy-nixon-1-of-4/2888.000-2910.500
- in PR: https://mytake-staging-pr-200.herokuapp.com/foundation-v1/presidential-debate-kennedy-nixon-1-of-4/2888.000-2910.500

**Comment by WebsByTodd** [comment] 2018-07-27 17:41
Very strange. When I first started looking into this I was able to reproduce the problem. I pressed the "Play Clip" button and the video played from the beginning, not from the start of the clip. I tried to scrub the video with the slider and the video didn't respond to the changes. 

After debugging for 15 minutes or so, it suddenly started working again. I changed nothing. I checked in prod and it was working there too. Tried again in an incognito browser and it was still working.

It's very hard to determine the source of this issue since we use the react-youtube library as a wrapper around the YouTube IFrame API. Either:

1. There's something wrong in our code. 
    - When I logged the props we send to the react-youtube component, they appear perfectly fine, but maybe there's something I'm overlooking.
2. There's something wrong in the react-youtube library.
    - I'm pretty sure this is the most widely used YouTube player for React and the issues tab of the repo is pretty quiet, which leads me to believe that it's very stable.
3. There's something wrong with the YouTube IFrame API.
    - Maybe if a video hasn't been watched in a while it goes into a dungeon where clips can't be retrieved on demand so easily. Who knows?

**Comment by nedtwigg** [comment] 2018-07-27 18:01
Ruh-roh.  Does this one work for you?

https://mytake.org/foundation-v1/presidential-debate-kennedy-nixon-1-of-4/2888.000-2910.500

It doesn't work for me right now.  If you have a link that works for you, can you send it to me and I'll try?

**Comment by WebsByTodd** [comment] 2018-07-27 18:05
Aha! If I click "Play Clip" then the issue appears. If I click the video itself to play it, then it plays the clip as expected. I'll keep investigating...

**Comment by WebsByTodd** [comment] 2018-07-27 19:04
I made a code change from `seekTo` to `playVideo` and the player is working as expected now. It's not clear why the previous player method wasn't always working or if it was ever working consistently before. See the [YouTube Player API docs](https://developers.google.com/youtube/iframe_api_reference) for reference.

**Closed by WebsByTodd** 2018-07-27 19:04 UTC
Labels: bug
